// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

var TableNames = struct {
	Books                string
	UserBookSubscription string
	Users                string
}{
	Books:                "books",
	UserBookSubscription: "user_book_subscription",
	Users:                "users",
}
